services:
  api:
    build: ./api-v1
    depends_on:
      - db
    ports:
      - "4435"
      - "4435:4435"
    links:
      - db

  db:
    container_name: memapp-test-1
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    #volumes:
    #  - type: volume
    #    source: memapp-test-vol-3
    #    target: /data/db

  client:
    build:
      context: ./client-2016
      dockerfile: Dockerfile-dev
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    links:
      - api
    volumes:
      - /etc/letsencrypt/live/www.ashphillips.com/:/etc/tls/:ro

#volumes:
#  memapp-test-vol-3:
