services:
  api:
    build: ./node-social
    depends_on:
      - db
    ports:
      - "4435"
      - "4435:4435"
    links:
      - db

  client:
    build: ./next-client
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    links:
      - api
    volumes:
      - /etc/tls/:/etc/tls/:ro
