services:
  api:
    build: ./node-social
    depends_on:
      - db
    ports:
      - "4435"
      - "4435:4435"
    links:
      - db

  client:
    build:
      context: ./next-client
      dockerfile: Dockerfile-dev
    depends_on:
      - api
    ports:
      - "3000:80"
      - "443:443"
    links:
      - api
